apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::123456789012:role/eks-develop-role
      username: dev-user
    - rolearn: arn:aws:iam::123456789012:role/eks-admin-role
      username: admin
      groups:
        - system:masters
  mapUsers: |
    []