apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  template:
    spec:
      containers:
      - name: user
        image: weaveworksdemos/user
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
