apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sock-shop
resources:
- ../../base
configMapGenerator:
- envs:
  - config.env
  name: config
patches:
- path: user.yaml
images:
- name: weaveworksdemos/user
  newTag: "0.4.7"