apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-end
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hi1280/sock-shop
    targetRevision: HEAD
    path: kubernetes/user/front-end/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true