apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: front-end
        resources:
          requests:
            cpu: 200m
            memory: 200Mi